import type { BatchSummary, Category, Product, UserProfile } from "./types";

export const mockCategories: Category[] = [
  {
    id: 1,
    slug: "fresh-fish",
    name: "Свежая рыба",
    description: "Улов и охлажденные позиции для запекания и гриля.",
    accent: "from-cyan-500/30 via-sky-500/10 to-white"
  },
  {
    id: 2,
    slug: "smoked",
    name: "Копченое",
    description: "Горячее и холодное копчение для закусок и стола.",
    accent: "from-amber-500/30 via-orange-500/10 to-white"
  },
  {
    id: 3,
    slug: "seafood",
    name: "Морепродукты",
    description: "Креветки, мидии и морские деликатесы.",
    accent: "from-teal-500/30 via-emerald-500/10 to-white"
  },
  {
    id: 4,
    slug: "semi-finished",
    name: "Полуфабрикаты",
    description: "Удобные позиции для семейного ужина и запаса.",
    accent: "from-rose-500/25 via-pink-500/10 to-white"
  }
];

export const mockProducts: Product[] = [
  {
    id: 101,
    wooProductId: 101,
    sku: "SALMON-STEAK",
    slug: "salmon-steak",
    name: "Стейк лосося охлажденный",
    categoryIds: [1],
    categoryNames: ["Свежая рыба"],
    shortDescription: "Плотный стейк для духовки и гриля.",
    fullDescription: "Охлажденный стейк лосося премиального качества. Хорошо подходит для запекания, стейков на гриле и домашних ужинов.",
    imageUrl: "/images/fish-steak.svg",
    accent: "from-orange-300 via-rose-200 to-white",
    price: 2190,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: true,
    isFeatured: true,
    isActive: true,
    relatedProductIds: [103, 109]
  },
  {
    id: 102,
    wooProductId: 102,
    sku: "COD-FILLET",
    slug: "cod-fillet",
    name: "Филе трески без кожи",
    categoryIds: [1],
    categoryNames: ["Свежая рыба"],
    shortDescription: "Нежное филе без лишней подготовки.",
    fullDescription: "Порционное филе трески без кожи и крупных костей. Подходит для жарки, тушения и детского меню.",
    imageUrl: "/images/white-fish.svg",
    accent: "from-sky-200 via-cyan-100 to-white",
    price: 1390,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: false,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [106, 108]
  },
  {
    id: 103,
    wooProductId: 103,
    sku: "SHRIMP-XL",
    slug: "shrimp-xl",
    name: "Креветка северная XL",
    categoryIds: [3],
    categoryNames: ["Морепродукты"],
    shortDescription: "Отборная креветка для пасты и закусок.",
    fullDescription: "Крупная северная креветка шоковой заморозки. Идеальна для салатов, пасты и праздничных закусок.",
    imageUrl: "/images/shellfish.svg",
    accent: "from-pink-300 via-rose-200 to-white",
    price: 1690,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: false,
    isFeatured: true,
    isActive: true,
    relatedProductIds: [101, 110]
  },
  {
    id: 104,
    wooProductId: 104,
    sku: "MUSSEL-MEAT",
    slug: "mussel-meat",
    name: "Мясо мидий",
    categoryIds: [3],
    categoryNames: ["Морепродукты"],
    shortDescription: "Для паэльи, пасты и сливочных соусов.",
    fullDescription: "Чистое мясо мидий без створок, удобно для быстрых блюд и ресторанной подачи дома.",
    imageUrl: "/images/shellfish.svg",
    accent: "from-teal-300 via-emerald-100 to-white",
    price: 890,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: true,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [103, 110]
  },
  {
    id: 105,
    wooProductId: 105,
    sku: "SMOKED-MACKEREL",
    slug: "smoked-mackerel",
    name: "Скумбрия горячего копчения",
    categoryIds: [2],
    categoryNames: ["Копченое"],
    shortDescription: "Ароматная скумбрия для стола и перекуса.",
    fullDescription: "Классическая скумбрия горячего копчения с плотным мясом и мягким ароматом дыма.",
    imageUrl: "/images/smoked.svg",
    accent: "from-amber-300 via-yellow-100 to-white",
    price: 760,
    currency: "RUB",
    unit: "pcs",
    isWeighted: false,
    isNew: false,
    isFeatured: true,
    isActive: true,
    relatedProductIds: [107, 111]
  },
  {
    id: 106,
    wooProductId: 106,
    sku: "POLLOCK-CUTLET",
    slug: "pollock-cutlet",
    name: "Котлеты из минтая",
    categoryIds: [4],
    categoryNames: ["Полуфабрикаты"],
    shortDescription: "Быстрый ужин без компромиссов по качеству.",
    fullDescription: "Рыбные котлеты ручной формовки. Удобно хранить в морозилке и быстро готовить на ужин.",
    imageUrl: "/images/pantry.svg",
    accent: "from-slate-300 via-zinc-100 to-white",
    price: 540,
    currency: "RUB",
    unit: "pack",
    isWeighted: false,
    isNew: false,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [102, 112]
  },
  {
    id: 107,
    wooProductId: 107,
    sku: "TROUT-SLICED",
    slug: "trout-sliced",
    name: "Форель слабосоленая нарезка",
    categoryIds: [2],
    categoryNames: ["Копченое"],
    shortDescription: "Праздничная подача и удобная упаковка.",
    fullDescription: "Тонкая нарезка слабосоленой форели в вакуумной упаковке. Для завтраков, брускетт и канапе.",
    imageUrl: "/images/smoked.svg",
    accent: "from-rose-300 via-orange-100 to-white",
    price: 690,
    currency: "RUB",
    unit: "pack",
    isWeighted: false,
    isNew: true,
    isFeatured: true,
    isActive: true,
    relatedProductIds: [105, 109]
  },
  {
    id: 108,
    wooProductId: 108,
    sku: "HAKE-CARCASS",
    slug: "hake-carcass",
    name: "Хек тушка",
    categoryIds: [1],
    categoryNames: ["Свежая рыба"],
    shortDescription: "Повседневная рыба для супов и запекания.",
    fullDescription: "Замороженная тушка хека среднего размера. Практичный вариант для семейных блюд.",
    imageUrl: "/images/white-fish.svg",
    accent: "from-blue-300 via-slate-100 to-white",
    price: 650,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: false,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [102, 106]
  },
  {
    id: 109,
    wooProductId: 109,
    sku: "SQUID-RINGS",
    slug: "squid-rings",
    name: "Кольца кальмара",
    categoryIds: [3],
    categoryNames: ["Морепродукты"],
    shortDescription: "Для жарки, темпуры и закусок.",
    fullDescription: "Ровные кольца кальмара, подходят для быстрого обжаривания и ресторанной подачи.",
    imageUrl: "/images/mix.svg",
    accent: "from-indigo-300 via-sky-100 to-white",
    price: 820,
    currency: "RUB",
    unit: "kg",
    isWeighted: true,
    isNew: false,
    isFeatured: true,
    isActive: true,
    relatedProductIds: [101, 107]
  },
  {
    id: 110,
    wooProductId: 110,
    sku: "SEAFOOD-MIX",
    slug: "seafood-mix",
    name: "Морской коктейль",
    categoryIds: [3],
    categoryNames: ["Морепродукты"],
    shortDescription: "Смесь для пасты, воков и супов.",
    fullDescription: "Креветка, кальмар, мидии и осьминог в одной упаковке. Универсальная позиция для быстрых блюд.",
    imageUrl: "/images/mix.svg",
    accent: "from-teal-300 via-cyan-100 to-white",
    price: 990,
    currency: "RUB",
    unit: "pack",
    isWeighted: false,
    isNew: true,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [103, 104]
  },
  {
    id: 111,
    wooProductId: 111,
    sku: "HERRING-FILLET",
    slug: "herring-fillet",
    name: "Филе сельди пряного посола",
    categoryIds: [2],
    categoryNames: ["Копченое"],
    shortDescription: "Классика для холодных закусок.",
    fullDescription: "Плотное филе сельди в пряном маринаде. Удобно подавать без дополнительной разделки.",
    imageUrl: "/images/smoked.svg",
    accent: "from-yellow-300 via-amber-100 to-white",
    price: 420,
    currency: "RUB",
    unit: "pack",
    isWeighted: false,
    isNew: false,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [105, 107]
  },
  {
    id: 112,
    wooProductId: 112,
    sku: "PIKE-DUMPLINGS",
    slug: "pike-dumplings",
    name: "Пельмени с щукой",
    categoryIds: [4],
    categoryNames: ["Полуфабрикаты"],
    shortDescription: "Редкая позиция для домашнего запаса.",
    fullDescription: "Сочные пельмени с начинкой из щуки. Подходят для быстрой варки и семейного ужина.",
    imageUrl: "/images/pantry.svg",
    accent: "from-fuchsia-200 via-rose-100 to-white",
    price: 610,
    currency: "RUB",
    unit: "pack",
    isWeighted: false,
    isNew: true,
    isFeatured: false,
    isActive: true,
    relatedProductIds: [106, 108]
  }
];

export const mockBatch: BatchSummary = {
  id: 1,
  batchId: "MURMANSK-2026-03A",
  title: "Сбор заявок на выдачу 20 марта",
  city: "Полярный",
  pickupPoint: "ул. Советская, 18, павильон у рынка",
  status: "open",
  startAt: "2026-03-06T06:00:00.000Z",
  endAt: "2026-03-16T20:00:00.000Z",
  pickupWindow: "20 марта, 12:00-16:00",
  isActive: true
};

export const demoUser: UserProfile = {
  telegramUserId: "100200300",
  telegramUsername: "seafood_fan",
  firstName: "Марина",
  lastName: "Кузнецова",
  phone: "+7 921 555-01-22",
  city: "Полярный",
  pickupPoint: "ул. Советская, 18, павильон у рынка"
};
